name: CD

on:
    push:
    pull_request:

jobs:
    audit:
        name: Build, Audit, Deploy
        runs-on: ubuntu-latest
        env:
            NODE_ENV: development

        steps:
            -   name: Checkout code
                uses: actions/checkout@v4

            -   name: Setup Node
                uses: actions/setup-node@v4
                with:
                    node-version: 18
                    registry-url: 'https://registry.npmjs.org'

            -   name: Install dependencies
                run: npm ci

            # No tests made yet.
            #-   name: Perform tests
            #    run: npm test

            -   name: Publish
                if: github.ref_type == 'tag'
                run: npm publish
                env:
                    NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_KEY }}
